### ISSUE TITLE
crash on many exemples

### ISSUE THREAD

**Issue by scenaristeur** [Amourspirit/python-ooouno-ex#317]
Hi, i have tried your examples but all crashes on my Mint ubuntu / Libreoffice 24.2.1. 
The documents open but not the dialogs, any idea ?

```
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/dialog/grid$ python start.py 
Opening /home/user/dev/python-ooouno-ex/ex/dialog/grid/data/sales_data.ods
Closing Office
Office link disposed
Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 874, in open_doc
    doc = loader.loadComponentFromURL(str(open_file_url), "_blank", 0, internal_props)  # type: ignore
uno.com.sun.star.uno.RuntimeException: Binary URP bridge disposed during call ./binaryurp/source/bridge.cxx:613

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/ex/dialog/grid/start.py", line 26, in <module>
    raise SystemExit(main())
  File "/home/user/dev/python-ooouno-ex/ex/dialog/grid/start.py", line 18, in main
    doc = CalcDoc.open_doc(fnm=fnm, visible=True)
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/utils/partial/doc_io_partial.py", line 782, in open_doc
    doc = lo_inst.open_doc(fnm=fnm, loader=loader, props=local_props)  # type: ignore
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 881, in open_doc
    raise Exception("Unable to open the document") from e
Exception: Unable to open the document
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/dialog/grid$ python start.py 
Opening /home/user/dev/python-ooouno-ex/ex/dialog/grid/data/sales_data.ods
Closing Office
Office link disposed
Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 874, in open_doc
    doc = loader.loadComponentFromURL(str(open_file_url), "_blank", 0, internal_props)  # type: ignore
uno.com.sun.star.uno.RuntimeException: Binary URP bridge disposed during call ./binaryurp/source/bridge.cxx:613

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/ex/dialog/grid/start.py", line 26, in <module>
    raise SystemExit(main())
  File "/home/user/dev/python-ooouno-ex/ex/dialog/grid/start.py", line 18, in main
    doc = CalcDoc.open_doc(fnm=fnm, visible=True)
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/utils/partial/doc_io_partial.py", line 782, in open_doc
    doc = lo_inst.open_doc(fnm=fnm, loader=loader, props=local_props)  # type: ignore
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 881, in open_doc
    raise Exception("Unable to open the document") from e
Exception: Unable to open the document
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/dialog/grid$ cd ../tree/
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/dialog/tree$ python start.py 
Creating Office document scalc
Closing Office
Office link disposed
Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 982, in create_doc
    doc = loader.loadComponentFromURL(f"private:factory/{dtype}", "_blank", 0, local_props)  # type: ignore
uno.com.sun.star.uno.RuntimeException: Binary URP bridge disposed during call ./binaryurp/source/bridge.cxx:613

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/ex/dialog/tree/start.py", line 25, in <module>
    raise SystemExit(main())
  File "/home/user/dev/python-ooouno-ex/ex/dialog/tree/start.py", line 16, in main
    doc = CalcDoc.create_doc(visible=True)
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/utils/partial/doc_io_partial.py", line 378, in create_doc
    doc = lo_inst.create_doc(doc_type=cls.DOC_TYPE.get_doc_type_str(), props=local_props)
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 987, in create_doc
    raise Exception("Could not create a document") from e
Exception: Could not create a document
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/dialog/tree$ 
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/dialog/tree$ cd ../../auto/writer/
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/auto/writer$ cd odev_text_replace/
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/auto/writer/odev_text_replace$ python start
python: can't open file '/home/user/dev/python-ooouno-ex/ex/auto/writer/odev_text_replace/start': [Errno 2] No such file or directory
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/auto/writer/odev_text_replace$ python start.py 
Unable to open the document
Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 874, in open_doc
    doc = loader.loadComponentFromURL(str(open_file_url), "_blank", 0, internal_props)  # type: ignore
uno.com.sun.star.uno.RuntimeException: Binary URP bridge disposed during call ./binaryurp/source/bridge.cxx:613

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/dev/python-ooouno-ex/ex/auto/writer/odev_text_replace/start.py", line 132, in <module>
    raise SystemExit(main())
  File "/home/user/dev/python-ooouno-ex/ex/auto/writer/odev_text_replace/start.py", line 88, in main
    doc = WriteDoc.open_doc(fnm=fnm, loader=loader, visible=True)
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/utils/partial/doc_io_partial.py", line 782, in open_doc
    doc = lo_inst.open_doc(fnm=fnm, loader=loader, props=local_props)  # type: ignore
  File "/home/user/dev/python-ooouno-ex/.venv/lib/python3.10/site-packages/ooodev/loader/inst/lo_inst.py", line 881, in open_doc
    raise Exception("Unable to open the document") from e
Exception: Unable to open the document
(.venv) user@user-IdeaPad:~/dev/python-ooouno-ex/ex/auto/writer/odev_text_replace$ 


```

**Comment by Amourspirit** [comment]
Looks like the example files are not available in this context.

How did you set up to run the examples? VirtualEnvornment?

If you run the examples in a Codespace (Development container) they will work.
BTW this repo is a codespace and can be run in your browser or in a supported Editor such as VS Code or Pycharm, althought I have not tried in PyCharm as Codespace yet.

**Comment by Amourspirit** [comment]
I should mentions also that I run this repo in a virtual environment on Ubuntu 22.04 without issue. I also run as a development container sometimes (uses docker).
